Commit IFC 4.3 Files Exported Via LF Works
bSI-InfraRoom/IFC-Tunnel-Deployment pull request #100
Opened 2023-03-21 20:48 UTC by jared-weston-seequent

## File

Upload 3 examples of exported files in IFC 4.3 format via LF Works.

Boreholes: Boreholes_ifc4_3_LeapfrogWorks2022_1_1.ifc
Geomodel: Geomodel_ifc4_3_LeapfrogWorks2022_1_1.ifc
Geoslice: Geoslice_ifc4_3_LeapfrogWorks2022_1_1.ifc

nb: no files for 4.4 yet. These files are likely to be the base for any 4.4 work Seequent will undertake.

2023-03-21 22:31 UTC, pjanck commented
Hi @jared-weston-seequent : thank you for submitting the files! As this is your first pull request, we (the project team) need to *manually* start the checking procedure (it's a GitHub *feature*). Please remain patient until we merge the first pull request. After that, the checker will run automatically, not needing our intervention.

If you wish to see why the files are failing, please consult the FAQ to see where to obtain the detailed report.

2023-03-21 23:06 UTC, pjanck commented
As for the errors, there seems to be a problem with the checker procedure. I'll have a look. Please wait.

2023-03-21 23:18 UTC, pjanck commented
I believe I have an idea where the problem lies: the checker does not recognize `IfcSolidStratum` entity, since in the Tunnel version of schema proposal (i.e. 4x4) this should be `IfcGeotechnicalStratum` (see [here](https://bsi-infraroom.github.io/IFC-Documentation-Tunnel/4_4_0_0/general/HTML/link/ifcgeotechnicalstratum.htm) with `PredefinedType=SOLID`.

2023-03-22 07:50 UTC, SergejMuhic commented
Are there no concepts from our sprints implemented?

Also, although the checker is not checking compositions (not part of any previous sprint yet), you have an issue with the placement of `IfcGeoslice`. It should have a placement referencing the placement of its container. In your case `IfcSite`. All the parts `IfcSolidStratum` placements should then reference the placement of `IfcGeoslice`.

2023-03-22 08:36 UTC, jared-weston-seequent commented
@SergejMuhic no not yet - we are looking for a home for existing 4.3 files and were instructed to submit them here along with 4.4 files when we create them. I will withdraw this PR and re-submit when we have something more appropriate 🤞 Thanks for having a look and all the feedback!

2023-03-22 08:42 UTC, SergejMuhic commented
No need to withdraw, failing in this deployment project setting is not the absence of success. We are all just working towards a good standard so any feedback and any datasets are good. We can use all input to work on a better schema, templates and usages and documentation.

2023-03-23 07:29 UTC, SergejMuhic commented
Have reopened according to https://github.com/bSI-InfraRoom/IFC-Tunnel-Deployment/pull/100#issuecomment-1479115265

2023-03-26 23:16 UTC, jared-weston-seequent commented
@SergejMuhic my understanding was that not all elements required placements- in this case, we have a parent entity (the geoslice) that acts as a container with no local placement of its own. Therefore we reference the child elements (the strata) back to the site rather than the non-existent placement of the geoslice. I'd rather not add a (0, 0, 0) placement when not required to avoid file size bloat. 

Would it be better if we just submitted files that matched what is covered in the sprints? Currently I see some files which are cut down and are only covering basics, e.g project set up, coordinate systems etc, and some which are fully fledged files (e.g that of trimble). 

I'm happy to add the modifications to replace `IfcSolidStratum` with `IfcGeotechnicalStratum` and `PredefinedType=SOLID` for now... Hopefully this will at least make the checker happy! 

![image](https://user-images.githubusercontent.com/56330434/227810523-cf243ed4-4b08-4dd3-a5bf-66eb4ababd75.png)

2023-03-27 02:50 UTC, jared-weston-seequent commented
Just a quick Q about project declaration. We don't do any of this at the moment. Is implementing this enforced in the schema / checker? I presume for our files, we would be able to define an `IfcActor` & assign the base site to this. At the moment we have no concept of 'who owns what' within a Leapfrog project, so I'm not sure we can do much more. Some things that would be nice would be to use the grouping relation to relate derived objects, e.g a model build from a set of boreholes. We also can access some coordinate system information on the example project so we can attempt the examples from sprint 2

2023-03-27 07:13 UTC, SergejMuhic commented
> @SergejMuhic my understanding was that not all elements required placements- in this case, we have a parent entity (the geoslice) that acts as a container with no local placement of its own.

Not all elements requiring placements is correct but in this context, the following template applies:
https://bsi-infraroom.github.io/IFC-Documentation-Tunnel/4_4_0_0/general/HTML/link/element-decomposition.htm
Specifically this part:
![image](https://user-images.githubusercontent.com/16683597/227865847-262d8fa0-c49f-4ebb-a5be-30edb6b1b089.png)

The children all reference the placement of the composite and only the composite is contained (containment template) in a spatial structure element.



> I'd rather not add a (0, 0, 0) placement when not required to avoid file size bloat.

The placement should only be (0,0,0) if the composite (the whole, your IfcGeoslice) is also placed at the origin of the site. It should be a local placement related to the site placement.


> Would it be better if we just submitted files that matched what is covered in the sprints?

That was the general idea. This way we work through the templates one by one and the discussion above might resolve itself. 😄 

The checker only check the sprints until now, so it will not check any Element Decompositions, just Spatial Decompositions.

2023-03-27 07:20 UTC, SergejMuhic commented
> Just a quick Q about project declaration. We don't do any of this at the moment. Is implementing this enforced in the schema / checker? I presume for our files, we would be able to define an `IfcActor` & assign the base site to this. At the moment we have no concept of 'who owns what' within a Leapfrog project, so I'm not sure we can do much more. Some things that would be nice would be to use the grouping relation to relate derived objects, e.g a model build from a set of boreholes. We also can access some coordinate system information on the example project so we can attempt the examples from sprint 2

Regarding declaration, please read:
https://bsi-infraroom.github.io/IFC-Documentation-Tunnel/4_4_0_0/general/HTML/link/project-declaration.htm
and
https://bsi-infraroom.github.io/IFC-Documentation-Tunnel/4_4_0_0/general/HTML/link/ifcproject.htm 
(scroll down or search for Project Declaration on the page)

Project as your root node of an IFC dataset requires all concepts to be attached to it. Apart from a few special cases such as classification and spatial decomposition, all concepts such as property set templates, libraries, types, groups or system etc. are supposed to be attached through declaration. If your software does not deal with IfcActor, I would suggest either leaving it empty or declaring one of the other possibilities that your software does support. Just add a note to your PR so that reviewers know why you modified a particular usage / concept. This way we can merge overriding the checker settings.

2023-04-11 04:20 UTC, jared-weston-seequent commented
I have made a much more cut-down version of this project for sprint 1.1. Sorry - a little behind as getting time to work on this is difficult, but this is probably easiest. The actual alignment work is not something LF supports so we will catch up with the 1.X sprints in the mean time.

I have added a dummy property set template and declared these on the project. We will eventually use this for defining borehole set properties, so I believe this is the most relevant way for us to progress here.

2023-04-13 06:23 UTC, larswik requested changes

2023-04-13 06:23 UTC, larswik commented on files/Seequent/LeapfrogWorksIFC_4_4_Sprint_1_1.ifc
> +#9=IFCGEOMETRICREPRESENTATIONCONTEXT($,'Model',3,1.0E-5,#8,$);
```suggestion
#9=IFCGEOMETRICREPRESENTATIONCONTEXT('3D','Model',3,1.0E-5,#8,$);
```

2023-04-13 09:33 UTC, pjanck commented
After the proposed fix by @larswik has been incorporated, we can merge this PR.

> I have added a dummy property set template and declared these on the project. We will eventually use this for defining borehole set properties, so I believe this is the most relevant way for us to progress here.

Great approach! There is a `WHERE` rule failing currently on the template, so make sure to fix that in the meantime as well.

2023-04-13 09:34 UTC, pjanck approved these changes
The file looks fine for sprint 1.1 - except for what @larswik has already noted.

2023-04-14 07:31 UTC, larswik approved these changes
lftm

2023-04-14 07:41 UTC, merged